### ISSUE TITLE
มีแพลนที่จะเปลี่ยนไปใช้ Github Team มีความคิดเห็นอย่างไรบ้าง

### ISSUE THREAD

**Issue by Pet002** [HanawuZ/nail-detection-2.0#14]
@HanawuZ @Pet002  คือตอนนี้เราใช้ Github ส่วนตัวอยู่แล้วคิดว่าถ้าเราย้ายไปใช้ GITHUB TEAM อาจจะดีในแง่ของการพัฒนา และก็การส่งต่อ Software ด้วยไหมอะ

เพราะGithub Team มันดูได้อะไรเยอะกว่า แต่อันนี้ต้องลองไปพิจารณาก่อนว่ามีข้อมจำกัดอะไรไหมด้วยนะ

**Comment by HanawuZ** [comment]
ส่วนตัวคิดว่าไม่จำเป็นเพราะพัฒนากันแค่ 2 คน
