### ISSUE TITLE
I find a problem when we use servo many time servo will missing position to nail

### ISSUE THREAD

**Issue by Pet002** [HanawuZ/nail-detection-2.0#36]
i found in case using a servo in a position 15 degree in many time (3 time more...) 
servo will stop in case press nail in a position 20-25 degree

how can we adjust?

should press servo in slowly

1. find some button to call a servo for stop servo
2. measure a voltage from servo (Hard)
3. detect from image if color is change to white (in nail) => will stop servo (Hard same)

**Comment by Pet002** [comment]
ใช้ pigpio ช่วยในการทำให้ Servo กดอยู่ที่เดิมเสมอๆ

**Comment by HanawuZ** [comment]
เปิดเครื่องทุกครั้งต้องทำการ run pigpiod ก่อนเสมอ
```sudo systemctl start pigpiod```
Ref:
https://raspberrypi.stackexchange.com/questions/70568/how-to-run-pigpiod-on-boot
